---
title: "multinichenet-hpc"
date: "2023-06-28"
output: html_document
params:
    args: ''
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width=12, fig.height=12) 
```

```{r packages}
library(SingleCellExperiment)
library(dplyr)
library(ggplot2)
library(multinichenetr)
library(Seurat)
library(SeuratDisk)
library(viridis)
```


```{r read-output}
multinichenet_output = readRDS("lilacs_multinichenet_pt_post_output.rds")
```

```{r get-vars}
celltype_info = multinichenet_output$abundance_expression_info$celltype_info
abundance_info = multinichenet_output$abundance_expression_info
celltype_de = multinichenet_output$celltype_de
DE_info = multinichenet_output$DE_info
sender_receiver_info = multinichenet_output$abundance_expression_info$sender_receiver_info
sender_receiver_de =  multinichenet_output$sender_receiver_de
ligand_activities_targets_DEgenes = multinichenet_output$ligand_activities_targets_DEgenes
prioritization_tables = multinichenet_output$prioritization_tables
grouping_tbl = multinichenet_output$grouping_tbl
lr_target_prior_cor = multinichenet_output$lr_target_prior_cor
```

``` {r set-params}
logFC_threshold = 0.50
p_val_threshold = 0.05
fraction_cutoff = 0.05

p_val_adj = FALSE

top_n_target = 250

verbose=TRUE

prioritizing_weights_DE = c("de_ligand" = 1,
                            "de_receptor" = 1)

prioritizing_weights_activity = c("activity_scaled" = 2)

prioritizing_weights_expression_specificity = c("exprs_ligand" = 2,
                                                "exprs_receptor" = 2)

prioritizing_weights_expression_sufficiency = c("frac_exprs_ligand_receptor" = 1)

prioritizing_weights_relative_abundance = c( "abund_sender" = 0,
                                             "abund_receiver" = 0)

prioritizing_weights = c(prioritizing_weights_DE, 
                         prioritizing_weights_activity, 
                         prioritizing_weights_expression_specificity,
                         prioritizing_weights_expression_sufficiency, 
                         prioritizing_weights_relative_abundance)
```


```{r load-nichenet-network}
options(timeout = 4000000) 

organism = "human"

load = FALSE

if(load == TRUE){
  lr_network = readRDS(url("https://zenodo.org/record/7074291/files/lr_network_human_21122021.rds"))
  lr_network = lr_network %>% 
    dplyr::rename(ligand = from, receptor = to) %>% 
    distinct(ligand, receptor) %>% 
    mutate(ligand = make.names(ligand), receptor = make.names(receptor))
    
  ligand_target_matrix = readRDS(url("https://zenodo.org/record/7074291/files/ligand_target_matrix_nsga2r_final.rds"))
  
  colnames(ligand_target_matrix) = colnames(ligand_target_matrix) %>% 
  make.names()

  rownames(ligand_target_matrix) = rownames(ligand_target_matrix) %>% 
  make.names()
}

if(load == FALSE){
  lr_network = readRDS("../mnn_networks/lr_network.rds")
  lr_network = lr_network %>% 
    dplyr::rename(ligand = from, receptor = to) %>% 
    distinct(ligand, receptor) %>% 
    mutate(ligand = make.names(ligand), receptor = make.names(receptor))
    
  ligand_target_matrix = readRDS("../mnn_networks/lr_network_matrix.rds")
  
  colnames(ligand_target_matrix) = colnames(ligand_target_matrix) %>% 
  make.names()

  rownames(ligand_target_matrix) = rownames(ligand_target_matrix) %>% 
  make.names()
}

contrasts_oi = c("'expanded-nonexpanded','nonexpanded-expanded'") 
contrast_tbl = tibble(contrast = c("expanded-nonexpanded","nonexpanded-expanded"), 
                      group = c("expanded","nonexpanded"))
```

```{r p-val-plot, fig.width=25, fig.height=10}
DE_info$hist_pvals
```

```{r get-abundance-info}
multinichenet_output$abundance_info$abund_plot_sample
```

```{r get-abundance-info}
multinichenet_output$abundance_info$abund_plot_group
```

```{r}
multinichenet_output$abundance_info
```

```{r print top-per-group}
prioritized_tbl_oi_expanded_all = get_top_n_lr_pairs(multinichenet_output$prioritization_tables, 100000000, groups_oi = "expanded")

prioritized_tbl_oi_nonexpanded_all = get_top_n_lr_pairs(multinichenet_output$prioritization_tables, 100000000, groups_oi = "nonexpanded")

write.csv(prioritized_tbl_oi_expanded_all, "expanded_all.csv")
write.csv(prioritized_tbl_oi_nonexpanded_all, "nonexpanded_all.csv")
```


```{r vizualize-ligand-act-analysis, fig.width=10, fig.height=10}
#cell-cell communication analysis

prioritized_tbl_oi_all = get_top_n_lr_pairs(multinichenet_output$prioritization_tables, 
                                            50, rank_per_group = FALSE)

prioritized_tbl_oi = multinichenet_output$prioritization_tables$group_prioritization_tbl %>%
  filter(id %in% prioritized_tbl_oi_all$id) %>%
  distinct(id, sender, receiver, ligand, receptor, group) %>% 
  left_join(prioritized_tbl_oi_all)

prioritized_tbl_oi$prioritization_score[is.na(prioritized_tbl_oi$prioritization_score)] = 0

senders_receivers = union(prioritized_tbl_oi$sender %>% 
                            unique(), prioritized_tbl_oi$receiver %>%
                            unique()) %>% sort()

colors = c("#e6194b", "#3cb44b", "#ffe119", "#4363d8", 
          "#f58231", "#911eb4", "#46f0f0", "#f032e6", 
          "#bcf60c", "#fabebe", "#008080", "#e6beff", 
          "#9a6324", "#fffac8", "#800000", "#aaffc3", 
          "#808000", "#ffd8b1", "#000075", "#808080", 
          "#ffffff", "#000000")

#colors_sender = viridis(length(senders_receivers), option = "magma") %>%
#  magrittr::set_names(senders_receivers)

#colors_receiver = viridis(length(senders_receivers), option = "magma") %>%
#  magrittr::set_names(senders_receivers)

colors_sender <- colors %>%
  magrittr::set_names(senders_receivers)
  
colors_receiver <- colors %>%
  magrittr::set_names(senders_receivers)

circos_list = make_circos_group_comparison(prioritized_tbl_oi, colors_sender, colors_receiver)
```

```{r vizualize-ligand-act-analysis-curated, fig.width=12, fig.height=12}
#cell-cell communication analysis

prioritized_tbl_oi_all_curated = get_top_n_lr_pairs(multinichenet_output$prioritization_tables, 
                                            100, rank_per_group = FALSE)

prioritized_tbl_oi_all_curated = prioritized_tbl_oi_all_curated %>% 
  filter(!grepl("HLA", ligand)) %>%
  filter(!grepl("HLA", receptor)) %>%
  filter(!grepl("CD4_Treg", receiver)) %>%
  #filter(!grepl("CD4", receiver)) %>%
  filter(!grepl("B_", receiver))
  

 prioritized_tbl_oi = multinichenet_output$prioritization_tables$group_prioritization_tbl %>%
  filter(id %in% prioritized_tbl_oi_all_curated$id) %>%
  distinct(id, sender, receiver, ligand, receptor, group) %>% 
  left_join(prioritized_tbl_oi_all_curated)

prioritized_tbl_oi$prioritization_score[is.na(prioritized_tbl_oi$prioritization_score)] = 0

senders_receivers = union(prioritized_tbl_oi$sender %>% 
                            unique(), prioritized_tbl_oi$receiver %>%
                            unique()) %>% sort()

colors = c("#808000", "#ffd8b1", "#000075", "#808080", 
          "#e6194b", "#3cb44b", "#4287f5", "#ffe119", 
          "#bcf60c", "#fabebe", "#008080", "#e6beff", 
          "#9a6324", "#fffac8", "#800000", "#aaffc3", 
          "#f58231", "#911eb4", "#46f0f0", "#f032e6", 
          "#ffffff", "#000000", "#4363d8" )

#colors_sender = viridis(length(senders_receivers), option = "magma") %>%
#  magrittr::set_names(senders_receivers)

#colors_receiver = viridis(length(senders_receivers), option = "magma") %>%
#  magrittr::set_names(senders_receivers)

colors_sender <- colors %>%
  magrittr::set_names(senders_receivers)
  
colors_receiver <- colors %>%
  magrittr::set_names(senders_receivers)

circos_list = make_circos_group_comparison(prioritized_tbl_oi, colors_sender, colors_receiver)
```

```{r ind-circos, fig.width=8, fig.height=8}
nonexp_curated = get_top_n_lr_pairs(multinichenet_output$prioritization_tables, 25, groups_oi = "nonexpanded") %>% 
  filter(!grepl("HLA", ligand)) %>%
  filter(!grepl("HLA", receptor)) %>%
  filter(!grepl("CD4_Treg", receiver)) %>%
  #filter(!grepl("CD4", receiver)) %>%
  filter(!grepl("B_", receiver))

exp_curated = get_top_n_lr_pairs(multinichenet_output$prioritization_tables, 25, groups_oi = "expanded") %>% 
  filter(!grepl("HLA", ligand)) %>%
  filter(!grepl("HLA", receptor)) %>%
  filter(!grepl("CD4_Treg", receiver)) %>%
  #filter(!grepl("CD4", receiver)) %>%
  filter(!grepl("B_", receiver))

circos_nonexpanded = make_circos_one_group(nonexp_curated, colors_sender, colors_receiver)

circos_expanded = make_circos_one_group(exp_curated, colors_sender, colors_receiver)
```

```{r vizualize-ligand-act-analysis-2}
#scaled ligand-receptor pseudobulk products and ligand activity

group_oi = "nonexpanded"
prioritized_tbl_oi_M_50 = get_top_n_lr_pairs(multinichenet_output$prioritization_tables, 100, groups_oi = group_oi)  %>% 
  filter(!grepl("HLA", ligand)) %>%
  filter(!grepl("HLA", receptor)) %>%
  filter(!grepl("CD4_Treg", receiver)) %>%
  filter(!grepl("CD4", receiver)) %>%
  filter(!grepl("B_", receiver))


ne_plot_oi = make_sample_lr_prod_activity_plots(multinichenet_output$prioritization_tables, prioritized_tbl_oi_M_50)
ne_plot_oi

group_oi = "expanded"
prioritized_tbl_oi_M_50 = get_top_n_lr_pairs(multinichenet_output$prioritization_tables, 100, groups_oi = group_oi) %>% 
  filter(!grepl("HLA", ligand)) %>%
  filter(!grepl("HLA", receptor)) %>%
  filter(!grepl("CD4_Treg", receiver)) %>%
  filter(!grepl("CD4", receiver)) %>%
  filter(!grepl("B_", receiver))

e_plot_oi = make_sample_lr_prod_activity_plots(multinichenet_output$prioritization_tables, prioritized_tbl_oi_M_50)
e_plot_oi
```

```{r vizualize-ligand-act-analysis-3}
# ligand-activity, ligand-target links, and target gene expression

group_oi = "nonexpanded"
receiver_oi = "Classical_mono"
prioritized_tbl_oi_M_10 = get_top_n_lr_pairs(multinichenet_output$prioritization_tables, 30, 
                                             groups_oi = group_oi, receivers_oi = receiver_oi) %>% 
  filter(!grepl("HLA", ligand)) %>%
  filter(!grepl("HLA", receptor)) %>%
  filter(!grepl("CD4_Treg", receiver)) %>%
  filter(!grepl("CD4", receiver))%>%
  filter(!grepl("B_", receiver))

combined_plot = make_ligand_activity_target_plot(group_oi, receiver_oi, 
                                                 prioritized_tbl_oi_M_10,
                                                 multinichenet_output$prioritization_tables,
                                              multinichenet_output$ligand_activities_targets_DEgenes,
                                                 contrast_tbl, 
                                                 multinichenet_output$grouping_tbl,
                                                 multinichenet_output$celltype_info, 
                                                 ligand_target_matrix, plot_legend = TRUE)
combined_plot


group_oi = "expanded"
receiver_oi = "Classical_mono"
prioritized_tbl_oi_M_10 = get_top_n_lr_pairs(multinichenet_output$prioritization_tables, 30, 
                                             groups_oi = group_oi, receivers_oi = receiver_oi) %>% 
  filter(!grepl("HLA", ligand)) %>%
  filter(!grepl("HLA", receptor)) %>%
  filter(!grepl("CD4_Treg", receiver)) %>%
  filter(!grepl("CD4", receiver))%>%
  filter(!grepl("B_", receiver))

combined_plot = make_ligand_activity_target_plot(group_oi, receiver_oi, 
                                                 prioritized_tbl_oi_M_10,
                                                 multinichenet_output$prioritization_tables,
                                              multinichenet_output$ligand_activities_targets_DEgenes,
                                                 contrast_tbl, 
                                                 multinichenet_output$grouping_tbl,
                                                 multinichenet_output$celltype_info, 
                                                 ligand_target_matrix, plot_legend = TRUE)
combined_plot

group_oi = "nonexpanded"
receiver_oi = "CD8_Temra"
prioritized_tbl_oi_M_10 = get_top_n_lr_pairs(multinichenet_output$prioritization_tables, 30, 
                                             groups_oi = group_oi, receivers_oi = receiver_oi) %>% 
  filter(!grepl("HLA", ligand)) %>%
  filter(!grepl("HLA", receptor)) %>%
  filter(!grepl("CD4_Treg", receiver)) %>%
  filter(!grepl("CD4", receiver))

combined_plot = make_ligand_activity_target_plot(group_oi, receiver_oi, 
                                                 prioritized_tbl_oi_M_10,
                                                 multinichenet_output$prioritization_tables,
                                              multinichenet_output$ligand_activities_targets_DEgenes,
                                                 contrast_tbl, 
                                                 multinichenet_output$grouping_tbl,
                                                 multinichenet_output$celltype_info, 
                                                 ligand_target_matrix, plot_legend = TRUE)
combined_plot


group_oi = "expanded"
receiver_oi = "CD8_Temra"
prioritized_tbl_oi_M_10 = get_top_n_lr_pairs(multinichenet_output$prioritization_tables, 30, 
                                             groups_oi = group_oi, receivers_oi = receiver_oi) %>% 
  filter(!grepl("HLA", ligand)) %>%
  filter(!grepl("HLA", receptor)) %>%
  filter(!grepl("CD4_Treg", receiver)) %>%
  filter(!grepl("CD4", receiver))

combined_plot = make_ligand_activity_target_plot(group_oi, receiver_oi, 
                                                 prioritized_tbl_oi_M_10,
                                                 multinichenet_output$prioritization_tables,
                                              multinichenet_output$ligand_activities_targets_DEgenes,
                                                 contrast_tbl, 
                                                 multinichenet_output$grouping_tbl,
                                                 multinichenet_output$celltype_info, 
                                                 ligand_target_matrix, plot_legend = TRUE)
combined_plot


group_oi = "nonexpanded"
receiver_oi = "Non.classical_mono"
prioritized_tbl_oi_M_10 = get_top_n_lr_pairs(multinichenet_output$prioritization_tables, 10, 
                                             groups_oi = group_oi, receivers_oi = receiver_oi)

combined_plot = make_ligand_activity_target_plot(group_oi, receiver_oi, 
                                                 prioritized_tbl_oi_M_10,
                                                 multinichenet_output$prioritization_tables,
                                              multinichenet_output$ligand_activities_targets_DEgenes,
                                                 contrast_tbl, 
                                                 multinichenet_output$grouping_tbl,
                                                 multinichenet_output$celltype_info, 
                                                 ligand_target_matrix, plot_legend = TRUE)
combined_plot


group_oi = "expanded"
receiver_oi = "Non.classical_mono"
prioritized_tbl_oi_M_10 = get_top_n_lr_pairs(multinichenet_output$prioritization_tables, 10, 
                                             groups_oi = group_oi, receivers_oi = receiver_oi)

combined_plot = make_ligand_activity_target_plot(group_oi, receiver_oi, 
                                                 prioritized_tbl_oi_M_10,
                                                 multinichenet_output$prioritization_tables,
                                              multinichenet_output$ligand_activities_targets_DEgenes,
                                                 contrast_tbl, 
                                                 multinichenet_output$grouping_tbl,
                                                 multinichenet_output$celltype_info, 
                                                 ligand_target_matrix, plot_legend = TRUE)
combined_plot


group_oi = "nonexpanded"
receiver_oi = "CD16pos_NK"
prioritized_tbl_oi_M_10 = get_top_n_lr_pairs(multinichenet_output$prioritization_tables, 10, 
                                             groups_oi = group_oi, receivers_oi = receiver_oi)

combined_plot = make_ligand_activity_target_plot(group_oi, receiver_oi, 
                                                 prioritized_tbl_oi_M_10,
                                                 multinichenet_output$prioritization_tables,
                                              multinichenet_output$ligand_activities_targets_DEgenes,
                                                 contrast_tbl, 
                                                 multinichenet_output$grouping_tbl,
                                                 multinichenet_output$celltype_info, 
                                                 ligand_target_matrix, plot_legend = TRUE)
combined_plot


group_oi = "expanded"
receiver_oi = "CD16pos_NK"
prioritized_tbl_oi_M_10 = get_top_n_lr_pairs(multinichenet_output$prioritization_tables, 10, 
                                             groups_oi = group_oi, receivers_oi = receiver_oi)

combined_plot = make_ligand_activity_target_plot(group_oi, receiver_oi, 
                                                 prioritized_tbl_oi_M_10,
                                                 multinichenet_output$prioritization_tables,
                                              multinichenet_output$ligand_activities_targets_DEgenes,
                                                 contrast_tbl, 
                                                 multinichenet_output$grouping_tbl,
                                                 multinichenet_output$celltype_info, 
                                                 ligand_target_matrix, plot_legend = TRUE)


combined_plot

group_oi = "nonexpanded"
receiver_oi = "cDC2"
prioritized_tbl_oi_M_10 = get_top_n_lr_pairs(multinichenet_output$prioritization_tables, 10, 
                                             groups_oi = group_oi, receivers_oi = receiver_oi)

combined_plot = make_ligand_activity_target_plot(group_oi, receiver_oi, 
                                                 prioritized_tbl_oi_M_10,
                                                 multinichenet_output$prioritization_tables,
                                              multinichenet_output$ligand_activities_targets_DEgenes,
                                                 contrast_tbl, 
                                                 multinichenet_output$grouping_tbl,
                                                 multinichenet_output$celltype_info, 
                                                 ligand_target_matrix, plot_legend = TRUE)
combined_plot


group_oi = "expanded"
receiver_oi = "cDC2"
prioritized_tbl_oi_M_10 = get_top_n_lr_pairs(multinichenet_output$prioritization_tables, 10, 
                                             groups_oi = group_oi, receivers_oi = receiver_oi)

combined_plot = make_ligand_activity_target_plot(group_oi, receiver_oi, 
                                                 prioritized_tbl_oi_M_10,
                                                 multinichenet_output$prioritization_tables,
                                              multinichenet_output$ligand_activities_targets_DEgenes,
                                                 contrast_tbl, 
                                                 multinichenet_output$grouping_tbl,
                                                 multinichenet_output$celltype_info, 
                                                 ligand_target_matrix, plot_legend = TRUE)
combined_plot

group_oi = "nonexpanded"
receiver_oi = "CD4_Tem"
prioritized_tbl_oi_M_10 = get_top_n_lr_pairs(multinichenet_output$prioritization_tables, 10, 
                                             groups_oi = group_oi, receivers_oi = receiver_oi)

combined_plot = make_ligand_activity_target_plot(group_oi, receiver_oi, 
                                                 prioritized_tbl_oi_M_10,
                                                 multinichenet_output$prioritization_tables,
                                              multinichenet_output$ligand_activities_targets_DEgenes,
                                                 contrast_tbl, 
                                                 multinichenet_output$grouping_tbl,
                                                 multinichenet_output$celltype_info, 
                                                 ligand_target_matrix, plot_legend = TRUE)
combined_plot


group_oi = "expanded"
receiver_oi = "CD4_Tem"
prioritized_tbl_oi_M_10 = get_top_n_lr_pairs(multinichenet_output$prioritization_tables, 10, 
                                             groups_oi = group_oi, receivers_oi = receiver_oi)

combined_plot = make_ligand_activity_target_plot(group_oi, receiver_oi, 
                                                 prioritized_tbl_oi_M_10,
                                                 multinichenet_output$prioritization_tables,
                                              multinichenet_output$ligand_activities_targets_DEgenes,
                                                 contrast_tbl, 
                                                 multinichenet_output$grouping_tbl,
                                                 multinichenet_output$celltype_info, 
                                                 ligand_target_matrix, plot_legend = TRUE)
combined_plot
```


```{r vizualize-ligand-act-analysis-4}
#expression-correlated target genes of ligand-receptor pairs w/ priors

group_oi = "nonexpanded"
receiver_oi = "Non.classical_mono_C1Q."

lr_target_prior_cor_filtered = multinichenet_output$lr_target_prior_cor %>%
  inner_join(ligand_activities_targets_DEgenes$ligand_activities %>%
  distinct(ligand, target, direction_regulation, contrast)) %>% 
  inner_join(contrast_tbl) %>% 
  filter(group == group_oi, receiver == receiver_oi)

lr_target_prior_cor_filtered_up = lr_target_prior_cor_filtered %>% 
  filter(direction_regulation == "up") %>% 
  filter( (rank_of_target < top_n_target) & (pearson > 0.50 | spearman > 0.50))

lr_target_prior_cor_filtered_down = lr_target_prior_cor_filtered %>%
  filter(direction_regulation == "down") %>% 
  filter( (rank_of_target < top_n_target) & (pearson < -0.50 | spearman < -0.50))

lr_target_prior_cor_filtered = bind_rows(lr_target_prior_cor_filtered_up, lr_target_prior_cor_filtered_down)


prioritized_tbl_oi = get_top_n_lr_pairs(prioritization_tables, 50, groups_oi = group_oi, receivers_oi = receiver_oi) %>% 
  filter(!grepl("HLA", ligand)) %>%
  filter(!grepl("HLA", receptor)) %>%
  filter(!grepl("CD4_Treg", receiver)) %>%
  filter(!grepl("CD4", receiver))

lr_target_correlation_plot = make_lr_target_correlation_plot(multinichenet_output$prioritization_tables, 
                                                             prioritized_tbl_oi,
                                                             lr_target_prior_cor_filtered,
                                                             multinichenet_output$grouping_tbl, 
                                                             multinichenet_output$celltype_info, 
                                                             receiver_oi,plot_legend = FALSE)
lr_target_correlation_plot$combined_plot

group_oi = "expanded"
receiver_oi = "Non.classical_mono_C1Q."

lr_target_prior_cor_filtered = multinichenet_output$lr_target_prior_cor %>%
  inner_join(ligand_activities_targets_DEgenes$ligand_activities %>%
  distinct(ligand, target, direction_regulation, contrast)) %>% 
  inner_join(contrast_tbl) %>% 
  filter(group == group_oi, receiver == receiver_oi)

lr_target_prior_cor_filtered_up = lr_target_prior_cor_filtered %>% 
  filter(direction_regulation == "up") %>% 
  filter( (rank_of_target < top_n_target) & (pearson > 0.50 | spearman > 0.50))

lr_target_prior_cor_filtered_down = lr_target_prior_cor_filtered %>%
  filter(direction_regulation == "down") %>% 
  filter( (rank_of_target < top_n_target) & (pearson < -0.50 | spearman < -0.50))

lr_target_prior_cor_filtered = bind_rows(lr_target_prior_cor_filtered_up, lr_target_prior_cor_filtered_down) 


prioritized_tbl_oi = get_top_n_lr_pairs(prioritization_tables, 100, 
                                        groups_oi = group_oi, receivers_oi = receiver_oi) %>% 
  filter(!grepl("HLA", ligand)) %>%
  filter(!grepl("HLA", receptor)) %>%
  filter(!grepl("CD4_Treg", receiver)) %>%
  filter(!grepl("CD4", receiver))

lr_target_correlation_plot = make_lr_target_correlation_plot(multinichenet_output$prioritization_tables, 
                                                             prioritized_tbl_oi,
                                                             lr_target_prior_cor_filtered,
                                                             multinichenet_output$grouping_tbl, 
                                                             multinichenet_output$celltype_info, 
                                                             receiver_oi,plot_legend = FALSE)
lr_target_correlation_plot$combined_plot


group_oi = "nonexpanded"
receiver_oi = "CD8_Temra"

lr_target_prior_cor_filtered = multinichenet_output$lr_target_prior_cor %>%
  inner_join(ligand_activities_targets_DEgenes$ligand_activities %>%
  distinct(ligand, target, direction_regulation, contrast)) %>% 
  inner_join(contrast_tbl) %>% 
  filter(group == group_oi, receiver == receiver_oi)

lr_target_prior_cor_filtered_up = lr_target_prior_cor_filtered %>% 
  filter(direction_regulation == "up") %>% 
  filter( (rank_of_target < top_n_target) & (pearson > 0.50 | spearman > 0.50))

lr_target_prior_cor_filtered_down = lr_target_prior_cor_filtered %>%
  filter(direction_regulation == "down") %>% 
  filter( (rank_of_target < top_n_target) & (pearson < -0.50 | spearman < -0.50))

lr_target_prior_cor_filtered = bind_rows(lr_target_prior_cor_filtered_up, lr_target_prior_cor_filtered_down)

prioritized_tbl_oi = get_top_n_lr_pairs(prioritization_tables, 200, groups_oi = group_oi, receivers_oi = receiver_oi) %>% 
  filter(!grepl("HLA", ligand)) %>%
  filter(!grepl("HLA", receptor)) %>%
  filter(!grepl("CD4_Treg", receiver)) %>%
  filter(!grepl("CD4", receiver))

lr_target_correlation_plot = make_lr_target_correlation_plot(multinichenet_output$prioritization_tables, 
                                                             prioritized_tbl_oi,
                                                             lr_target_prior_cor_filtered,
                                                             multinichenet_output$grouping_tbl, 
                                                             multinichenet_output$celltype_info, 
                                                             receiver_oi,plot_legend = FALSE)
lr_target_correlation_plot$combined_plot

group_oi = "expanded"
receiver_oi = "CD8_Temra"

lr_target_prior_cor_filtered = multinichenet_output$lr_target_prior_cor %>%
  inner_join(ligand_activities_targets_DEgenes$ligand_activities %>%
  distinct(ligand, target, direction_regulation, contrast)) %>% 
  inner_join(contrast_tbl) %>% 
  filter(group == group_oi, receiver == receiver_oi)

lr_target_prior_cor_filtered_up = lr_target_prior_cor_filtered %>% 
  filter(direction_regulation == "up") %>% 
  filter( (rank_of_target < top_n_target) & (pearson > 0.50 | spearman > 0.50))

lr_target_prior_cor_filtered_down = lr_target_prior_cor_filtered %>%
  filter(direction_regulation == "down") %>% 
  filter( (rank_of_target < top_n_target) & (pearson < -0.50 | spearman < -0.50))

lr_target_prior_cor_filtered = bind_rows(lr_target_prior_cor_filtered_up, lr_target_prior_cor_filtered_down)

prioritized_tbl_oi = get_top_n_lr_pairs(prioritization_tables, 200, 
                                        groups_oi = group_oi, receivers_oi = receiver_oi) %>% 
  filter(!grepl("HLA", ligand)) %>%
  filter(!grepl("HLA", receptor)) %>%
  filter(!grepl("CD4_Treg", receiver)) %>%
  filter(!grepl("CD4", receiver))

lr_target_correlation_plot = make_lr_target_correlation_plot(multinichenet_output$prioritization_tables, 
                                                             prioritized_tbl_oi,
                                                             lr_target_prior_cor_filtered,
                                                             multinichenet_output$grouping_tbl, 
                                                             multinichenet_output$celltype_info, 
                                                             receiver_oi,plot_legend = FALSE)
lr_target_correlation_plot$combined_plot




group_oi = "nonexpanded"
receiver_oi = "CD16pos_NK"

lr_target_prior_cor_filtered = multinichenet_output$lr_target_prior_cor %>%
  inner_join(ligand_activities_targets_DEgenes$ligand_activities %>%
  distinct(ligand, target, direction_regulation, contrast)) %>% 
  inner_join(contrast_tbl) %>% 
  filter(group == group_oi, receiver == receiver_oi)

lr_target_prior_cor_filtered_up = lr_target_prior_cor_filtered %>% 
  filter(direction_regulation == "up") %>% 
  filter( (rank_of_target < top_n_target) & (pearson > 0.50 | spearman > 0.50))

lr_target_prior_cor_filtered_down = lr_target_prior_cor_filtered %>%
  filter(direction_regulation == "down") %>% 
  filter( (rank_of_target < top_n_target) & (pearson < -0.50 | spearman < -0.50))

lr_target_prior_cor_filtered = bind_rows(lr_target_prior_cor_filtered_up, lr_target_prior_cor_filtered_down)

prioritized_tbl_oi = get_top_n_lr_pairs(prioritization_tables, 50, groups_oi = group_oi, receivers_oi = receiver_oi) %>% 
  filter(!grepl("HLA", ligand)) %>%
  filter(!grepl("HLA", receptor)) %>%
  filter(!grepl("CD4_Treg", receiver)) %>%
  filter(!grepl("CD4", receiver))

lr_target_correlation_plot = make_lr_target_correlation_plot(multinichenet_output$prioritization_tables, 
                                                             prioritized_tbl_oi,
                                                             lr_target_prior_cor_filtered,
                                                             multinichenet_output$grouping_tbl, 
                                                             multinichenet_output$celltype_info, 
                                                             receiver_oi,plot_legend = FALSE)
lr_target_correlation_plot$combined_plot

group_oi = "expanded"
receiver_oi = "CD16pos_NK"

lr_target_prior_cor_filtered = multinichenet_output$lr_target_prior_cor %>%
  inner_join(ligand_activities_targets_DEgenes$ligand_activities %>%
  distinct(ligand, target, direction_regulation, contrast)) %>% 
  inner_join(contrast_tbl) %>% 
  filter(group == group_oi, receiver == receiver_oi)

lr_target_prior_cor_filtered_up = lr_target_prior_cor_filtered %>% 
  filter(direction_regulation == "up") %>% 
  filter( (rank_of_target < top_n_target) & (pearson > 0.50 | spearman > 0.50))

lr_target_prior_cor_filtered_down = lr_target_prior_cor_filtered %>%
  filter(direction_regulation == "down") %>% 
  filter( (rank_of_target < top_n_target) & (pearson < -0.50 | spearman < -0.50))

lr_target_prior_cor_filtered = bind_rows(lr_target_prior_cor_filtered_up, lr_target_prior_cor_filtered_down)

prioritized_tbl_oi = get_top_n_lr_pairs(prioritization_tables, 50, 
                                        groups_oi = group_oi, receivers_oi = receiver_oi)

lr_target_correlation_plot = make_lr_target_correlation_plot(multinichenet_output$prioritization_tables, 
                                                             prioritized_tbl_oi,
                                                             lr_target_prior_cor_filtered,
                                                             multinichenet_output$grouping_tbl, 
                                                             multinichenet_output$celltype_info, 
                                                             receiver_oi,plot_legend = FALSE)
lr_target_correlation_plot$combined_plot


group_oi = "expanded"
receiver_oi = "cDC2"

lr_target_prior_cor_filtered = multinichenet_output$lr_target_prior_cor %>%
  inner_join(ligand_activities_targets_DEgenes$ligand_activities %>%
  distinct(ligand, target, direction_regulation, contrast)) %>% 
  inner_join(contrast_tbl) %>% 
  filter(group == group_oi, receiver == receiver_oi)

lr_target_prior_cor_filtered_up = lr_target_prior_cor_filtered %>% 
  filter(direction_regulation == "up") %>% 
  filter( (rank_of_target < top_n_target) & (pearson > 0.50 | spearman > 0.50))

lr_target_prior_cor_filtered_down = lr_target_prior_cor_filtered %>%
  filter(direction_regulation == "down") %>% 
  filter( (rank_of_target < top_n_target) & (pearson < -0.50 | spearman < -0.50))

lr_target_prior_cor_filtered = bind_rows(lr_target_prior_cor_filtered_up, lr_target_prior_cor_filtered_down)

prioritized_tbl_oi = get_top_n_lr_pairs(prioritization_tables, 50, 
                                        groups_oi = group_oi, receivers_oi = receiver_oi) %>% 
  filter(!grepl("HLA", ligand)) %>%
  filter(!grepl("HLA", receptor)) %>%
  filter(!grepl("CD4_Treg", receiver)) %>%
  filter(!grepl("CD4", receiver))

lr_target_correlation_plot = make_lr_target_correlation_plot(multinichenet_output$prioritization_tables, 
                                                             prioritized_tbl_oi,
                                                             lr_target_prior_cor_filtered,
                                                             multinichenet_output$grouping_tbl, 
                                                             multinichenet_output$celltype_info, 
                                                             receiver_oi,plot_legend = FALSE)
lr_target_correlation_plot$combined_plot

group_oi = "nonexpanded"
receiver_oi = "CD4_Tem"

lr_target_prior_cor_filtered = multinichenet_output$lr_target_prior_cor %>%
  inner_join(ligand_activities_targets_DEgenes$ligand_activities %>%
  distinct(ligand, target, direction_regulation, contrast)) %>% 
  inner_join(contrast_tbl) %>% 
  filter(group == group_oi, receiver == receiver_oi)

lr_target_prior_cor_filtered_up = lr_target_prior_cor_filtered %>% 
  filter(direction_regulation == "up") %>% 
  filter( (rank_of_target < top_n_target) & (pearson > 0.50 | spearman > 0.50))

lr_target_prior_cor_filtered_down = lr_target_prior_cor_filtered %>%
  filter(direction_regulation == "down") %>% 
  filter( (rank_of_target < top_n_target) & (pearson < -0.50 | spearman < -0.50))

lr_target_prior_cor_filtered = bind_rows(lr_target_prior_cor_filtered_up, lr_target_prior_cor_filtered_down)

prioritized_tbl_oi = get_top_n_lr_pairs(prioritization_tables, 50, groups_oi = group_oi, receivers_oi = receiver_oi)

lr_target_correlation_plot = make_lr_target_correlation_plot(multinichenet_output$prioritization_tables, 
                                                             prioritized_tbl_oi,
                                                             lr_target_prior_cor_filtered,
                                                             multinichenet_output$grouping_tbl, 
                                                             multinichenet_output$celltype_info, 
                                                             receiver_oi,plot_legend = FALSE)
lr_target_correlation_plot$combined_plot


group_oi = "expanded"
receiver_oi = "CD4_Tem"

lr_target_prior_cor_filtered = multinichenet_output$lr_target_prior_cor %>%
  inner_join(ligand_activities_targets_DEgenes$ligand_activities %>%
  distinct(ligand, target, direction_regulation, contrast)) %>% 
  inner_join(contrast_tbl) %>% 
  filter(group == group_oi, receiver == receiver_oi)

lr_target_prior_cor_filtered_up = lr_target_prior_cor_filtered %>% 
  filter(direction_regulation == "up") %>% 
  filter( (rank_of_target < top_n_target) & (pearson > 0.50 | spearman > 0.50))

lr_target_prior_cor_filtered_down = lr_target_prior_cor_filtered %>%
  filter(direction_regulation == "down") %>% 
  filter( (rank_of_target < top_n_target) & (pearson < -0.50 | spearman < -0.50))

lr_target_prior_cor_filtered = bind_rows(lr_target_prior_cor_filtered_up, lr_target_prior_cor_filtered_down)

prioritized_tbl_oi = get_top_n_lr_pairs(prioritization_tables, 50, 
                                        groups_oi = group_oi, receivers_oi = receiver_oi) 
lr_target_correlation_plot = make_lr_target_correlation_plot(multinichenet_output$prioritization_tables, 
                                                             prioritized_tbl_oi,
                                                             lr_target_prior_cor_filtered,
                                                             multinichenet_output$grouping_tbl, 
                                                             multinichenet_output$celltype_info, 
                                                             receiver_oi,plot_legend = FALSE)
lr_target_correlation_plot$combined_plot
```
```{r ligand-act-all}
ligands_oi = multinichenet_output$prioritization_tables$ligand_activities_target_de_tbl %>% inner_join(contrast_tbl) %>% 
  group_by(group, receiver) %>% distinct(ligand, receiver, group, activity) %>% 
  top_n(5, activity) %>% pull(ligand) %>% unique()

plot_oi = make_ligand_activity_plots(multinichenet_output$prioritization_tables, ligands_oi, contrast_tbl, widths = NULL)
plot_oi
```


```{r vizualize-ligand-act-analysis-5}
# intercellular regulatory network system
prioritized_tbl_oi = get_top_n_lr_pairs(prioritization_tables, 150, rank_per_group = FALSE) #default = FALSE, 150

lr_target_prior_cor_filtered = prioritization_tables$group_prioritization_tbl$group %>% unique() %>% 
  lapply(function(group_oi){
    lr_target_prior_cor_filtered = multinichenet_output$lr_target_prior_cor %>%
      inner_join(ligand_activities_targets_DEgenes$ligand_activities %>% 
                  distinct(ligand, target, direction_regulation, contrast)) %>%
                  inner_join(contrast_tbl) %>% 
                  filter(group == group_oi)
    
    lr_target_prior_cor_filtered_up = lr_target_prior_cor_filtered %>% 
      filter(direction_regulation == "up") %>% 
      filter( (rank_of_target < top_n_target) & (pearson > 0.50 | spearman > 0.50))
     
    lr_target_prior_cor_filtered_down = lr_target_prior_cor_filtered %>%
      filter(direction_regulation == "down") %>% 
      filter( (rank_of_target < top_n_target) & (pearson < -0.50 | spearman < -0.50))
      
    lr_target_prior_cor_filtered = bind_rows(lr_target_prior_cor_filtered_up,
                                               lr_target_prior_cor_filtered_down)
  }) %>% bind_rows()

#colors_sender["CD4.Central.Memory"] = "red"

graph_plot = make_ggraph_ligand_target_links(lr_target_prior_cor_filtered = lr_target_prior_cor_filtered, prioritized_tbl_oi = prioritized_tbl_oi, colors = colors_sender)

graph_plot$plot
```


```{r prior-knowledge-net-db}
organism = "human"

sig_network = readRDS(url("https://zenodo.org/record/7074291/files/signaling_network_human_21122021.rds")) %>% mutate(from = make.names(from), to = make.names(to))
  
gr_network = readRDS(url("https://zenodo.org/record/7074291/files/gr_network_human_21122021.rds")) %>% mutate(from = make.names(from), to = make.names(to))
  
ligand_tf_matrix = readRDS(url("https://zenodo.org/record/7074291/files/ligand_tf_matrix_nsga2r_final.rds"))
colnames(ligand_tf_matrix) = colnames(ligand_tf_matrix) %>% make.names()
rownames(ligand_tf_matrix) = rownames(ligand_tf_matrix) %>% make.names()
weighted_networks = readRDS(url("https://zenodo.org/record/7074291/files/weighted_networks_nsga2r_final.rds"))
weighted_networks$lr_sig = weighted_networks$lr_sig %>% mutate(from = make.names(from), to = make.names(to))
weighted_networks$gr = weighted_networks$gr %>% mutate(from = make.names(from), to = make.names(to))
```

```{r prior-knowledge-net}

ligand_oi = "TGFB1"
receptor_oi = "TGFBR3"
sender_oi = "CD4_Treg"
receiver_oi = "CD16pos_NK"

#lr_target_scatter_plot = make_lr_target_scatter_plot(multinichenet_output$prioritization_tables, ligand_oi, receptor_oi, sender_oi, #receiver_oi, multinichenet_output$celltype_info, multinichenet_output$grouping_tbl, lr_target_prior_cor_filtered)
#lr_target_scatter_plot

targets_all = lr_target_prior_cor_filtered %>% 
  filter(ligand == ligand_oi & receiver == receiver_oi & sender == sender_oi & receptor == receptor_oi)  %>% 
  pull(target) %>% 
  unique()
  
active_signaling_network = nichenetr::get_ligand_signaling_path_with_receptor(ligand_tf_matrix = ligand_tf_matrix, ligands_all = ligand_oi, receptors_all = receptor_oi, targets_all = targets_all, weighted_networks = weighted_networks, top_n_regulators = 2)

data_source_network = nichenetr::infer_supporting_datasources(signaling_graph_list = active_signaling_network,lr_network = lr_network, sig_network = sig_network, gr_network = gr_network)
  
active_signaling_network_min_max = active_signaling_network
active_signaling_network_min_max$sig = active_signaling_network_min_max$sig %>% mutate(weight = ((weight-min(weight))/(max(weight)-min(weight))) + 0.75)
active_signaling_network_min_max$gr = active_signaling_network_min_max$gr %>% mutate(weight = ((weight-min(weight))/(max(weight)-min(weight))) + 0.75)
colors = c("ligand" = "purple", "receptor" = "orange", "target" = "royalblue", "mediator" = "grey60")
ggraph_signaling_path = suppressWarnings(make_ggraph_signaling_path(active_signaling_network_min_max, colors, ligand_oi, receptor_oi, targets_all))
ggraph_signaling_path$plot
```

