---
title: "jack_bulkPipeline"
author: "agc57"
date: "2024-06-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libs}
library(dplyr)
library(edgeR)
library(janitor)
library(EnhancedVolcano)
library(org.Hs.eg.db)
library(fgsea)
library(stringr)
library(magrittr)
library(ggrepel)
library(data.table)
library(readxl)
```

```{r pre-process}
data <- read_excel("expandedvnonexpandedDEGs.xlsx")
```


```{r volcano, fig.width=6, fig.height=6}

lab_italics <- paste0("italic('", data$expanded_names, "')")
selectLab_italics = paste0(
    "italic('",
    c('IL32',
                 'CTSC',
                 'CD27',
                 'RPS6',
                 'RPL10',
                 'IFITM1',
                 'VIM',
                 'SAT1',
                 'RPS29',
                 'CD2',
                 'MYL6',
                 'LGALS3',
                 'ENO1',
                 'GAPDH',
                 'TPT1',
                 'CST7',
                 'TMEM173',
                  'LY6E'), "')")

EnhancedVolcano(data,
    lab = lab_italics, 
    x = 'expanded_logfoldchanges',
    y = 'expanded_pvals_adj',
    title="expanded Tregs vs. nonexpanded Tregs",
    subtitle = "Differential gene expression",
    ylim = c(0, 9),
    xlim = c(-1.5, 1.5),
    pCutoff = 0.05,
    FCcutoff = 0.3,
    pointSize = 5.0,
    gridlines.major = FALSE,
    gridlines.minor = FALSE,
    labSize = 8.0,
    labCol = 'black',
    selectLab = selectLab_italics,
    parseLabels = TRUE,
    boxedLabels = TRUE,
    col=c('black', 'black', 'black', 'blue'),
    colAlpha = 3/5,
    drawConnectors = TRUE,
    widthConnectors = 0.5,
    colConnectors = 'black',
    labFace = 'bold')
```

```{r pre-process}
data <- read.csv("nonTregCD4_Exp_v_NonExp.csv")
```

```{r volcano, fig.width=8, fig.height=8}
EnhancedVolcano(data,
    lab = data$expanded_names, 
    x = 'expanded_logfoldchanges',
    y = 'expanded_pvals_adj',
    title="expanded CD4+ non-Tregs vs. nonexpanded CD4+ non-Tregs",
    subtitle = "Differential gene expression",
    ylim = c(0, 150),
    xlim = c(-2.5, 2.5),
    pCutoff = 0.05,
    FCcutoff = 0.3)
```


```{r pre-process}
#data_up <- read.csv("nonTregCD4_UP_Pathways.csv")
#data_dn <- read.csv("nonTregCD4_DOWN_Pathways.csv")
```

```{r pathway, fig.width=15, fig.height=4}
ranked_list <- read.csv("/Users/caseag/Desktop/Mallat Lab/TCR paper draft/trimmed_ExpandedTRegGSEA.csv", header = T, stringsAsFactors = F)


ranked_list %>% 
  mutate(short_name = Term)%>% arrange (desc(fNES)) %>% 
  dplyr::select (Term, `FDR.q.val`, fNES) %>% head(25)

waterfall_plot <- function (ranked_list, graph_title) {
  ranked_list %>%
    mutate(type = str_split_fixed(Term, "_",2)[,1])%>%
    mutate(short_name = case_when(type == "GO"~ (str_split_fixed(Term, "__",2)[,2]),
                                 type == "KEGG" ~ (str_split_fixed(Term, "__",2)[,2]),
                                 type == "MSigDB" ~ (str_split_fixed(Term, "__",2)[,2]))) %>%
    mutate(short_name = case_when(type == "GO"~ (sub(" \\(.*\\)$", "", short_name)),
                                 type == "KEGG" ~ short_name,
                                 type == "MSigDB" ~ short_name)) %>%
    mutate(short_name = toupper(short_name)) %>%
    mutate(direction = case_when(fNES > 0 ~ "up",
                            fNES < 0 ~ "down")) %>%
    mutate(direction = factor(direction, levels = c("up", "down"))) %>%
    mutate(neg.log.FDR.q.val = -log(FDR.q.val, 10)) %>%
    ggplot( aes(reorder(short_name,fNES), fNES)) +
      #geom_bar(stat= "identity", aes(fill = type, alpha=neg.log.FDR.q.val)) +
      geom_bar(stat= "identity", 
               aes(fill=direction, 
                   alpha=neg.log.FDR.q.val)) +
      scale_alpha(range = c(0.4, 1)) +
      geom_point(aes(color=type), y=-3.1, shape=15, size=8) +
      coord_flip()+
      labs(x = "Pathway", y = "Normalized Enrichment Score", title = graph_title)+
      theme(axis.text.y = element_text(size = 28), 
            plot.title = element_text(hjust = 1)) +
    theme_minimal()
}

waterfall_plot(ranked_list, "Pathways: Expanded vs. Nonexpanded Tregs")
```

```{r pathway, fig.width=12, fig.height=12}
ranked_list <- read.csv("/Users/caseag/Desktop/Mallat Lab/TCR paper draft/NonTRegGSEA.csv", header = T, stringsAsFactors = F)

ranked_list %>% arrange (desc(NES)) %>% dplyr::select (Term, `FDR.q.val`, NES) %>% head(20)

waterfall_plot <- function (ranked_list, graph_title) {
  ranked_list %>% 
    mutate(short_name = str_split_fixed(Term, "_",2)[,2])%>% # removes 'HALLMARK_' from the pathway title 
    ggplot( aes(reorder(short_name,NES), NES)) +
      #geom_bar(stat= "identity", aes(fill = FDR.q.val<0.05))+
      geom_bar(stat= "identity", aes(fill = FDR.q.val))+
      coord_flip()+
      labs(x = "Hallmark Pathway", y = "Normalized Enrichment Score", title = graph_title)+
      theme(axis.text.y = element_text(size = 12), 
            plot.title = element_text(hjust = 1)) +
    theme_minimal()
}

waterfall_plot(ranked_list, "Pathways: Expanded vs. Nonexpanded CD4+ Non-Tregs")
```